local ctg_loot = {
    { name = '3d_armor:boots_steel',        chance = 0.15, y = { -5499, -1000 } },
    { name = '3d_armor:chestplate_steel',   chance = 0.15, y = { -5499, -1000 } },
    { name = '3d_armor:helmet_steel',       chance = 0.15, y = { -5499, -1000 } },
    { name = '3d_armor:leggings_steel',     chance = 0.15, y = { -5499, -1000 } },
    { name = 'shields:shield_steel',        chance = 0.15, y = { -5499, -1000 } },
    { name = 'default:sword_steel',         chance = 0.15, y = { -5499, -1000 } },
    { name = 'default:pick_steel',          chance = 0.15, y = { -5499, -1000 } },
    { name = 'default:shovel_steel',        chance = 0.15, y = { -5499, -1000 } },
    { name = '3d_armor:boots_steel',        chance = 0.3,  y = { -11000, -5500 } },
    { name = '3d_armor:chestplate_steel',   chance = 0.3,  y = { -11000, -5500 } },
    { name = '3d_armor:helmet_steel',       chance = 0.3,  y = { -11000, -5500 } },
    { name = '3d_armor:leggings_steel',     chance = 0.3,  y = { -11000, -5500 } },
    { name = 'shields:shield_steel',        chance = 0.3,  y = { -11000, -5500 } },
    { name = 'default:sword_steel',         chance = 0.3,  y = { -11000, -5500 } },
    { name = 'default:pick_steel',          chance = 0.3,  y = { -11000, -5500 } },
    { name = 'default:shovel_steel',        chance = 0.3,  y = { -11000, -5500 } },
    { name = '3d_armor:boots_diamond',      chance = 0.15, y = { -8999, -7000 } },
    { name = '3d_armor:chestplate_diamond', chance = 0.15, y = { -8999, -7000 } },
    { name = '3d_armor:helmet_diamond',     chance = 0.15, y = { -8999, -7000 } },
    { name = '3d_armor:leggings_diamond',   chance = 0.15, y = { -8999, -7000 } },
    { name = 'shields:shield_diamond',      chance = 0.15, y = { -8999, -7000 } },
    { name = 'default:sword_diamond',       chance = 0.15, y = { -8999, -7000 } },
    { name = 'default:pick_diamond',        chance = 0.15, y = { -8999, -7000 } },
    { name = 'default:shovel_diamond',      chance = 0.15, y = { -8999, -7000 } },
    { name = '3d_armor:boots_diamond',      chance = 0.3,  y = { -11000, -9000 } },
    { name = '3d_armor:chestplate_diamond', chance = 0.3,  y = { -11000, -9000 } },
    { name = '3d_armor:helmet_diamond',     chance = 0.3,  y = { -11000, -9000 } },
    { name = '3d_armor:leggings_diamond',   chance = 0.3,  y = { -11000, -9000 } },
    { name = 'shields:shield_diamond',      chance = 0.3,  y = { -11000, -9000 } },
    { name = 'default:sword_diamond',       chance = 0.3,  y = { -11000, -9000 } },
    { name = 'default:pick_diamond',        chance = 0.3,  y = { -11000, -9000 } },
    { name = 'default:shovel_diamond',      chance = 0.3,  y = { -11000, -9000 } },
    { name = '3d_armor:boots_mithril',      chance = 0.15, y = { -11000, -9500 } },
    { name = '3d_armor:chestplate_mithril', chance = 0.15, y = { -11000, -9500 } },
    { name = '3d_armor:helmet_mithril',     chance = 0.15, y = { -11000, -9500 } },
    { name = '3d_armor:leggings_mithril',   chance = 0.15, y = { -11000, -9500 } },
    { name = 'shields:shield_mithril',      chance = 0.15, y = { -11000, -9500 } },
    { name = 'moreores:sword_mithril',      chance = 0.15, y = { -11000, -9500 } },
    { name = 'moreores:pick_mithril',       chance = 0.15, y = { -11000, -9500 } },
    { name = 'moreores:shovel_mithril',     chance = 0.15, y = { -11000, -9500 } },
    { name = '3d_armor:boots_cactus',       chance = 0.3,  types = { "desert" } },
    { name = '3d_armor:chestplate_cactus',  chance = 0.3,  types = { "desert" } },
    { name = '3d_armor:helmet_cactus',      chance = 0.3,  types = { "desert" } },
    { name = '3d_armor:leggings_cactus',    chance = 0.3,  types = { "desert" } },
    { name = 'shields:shield_cactus',       chance = 0.3,  types = { "desert" } },
    { name = '3d_armor:boots_gold',         chance = 0.3,  types = { "sandstone" } },
    { name = '3d_armor:chestplate_gold',    chance = 0.3,  types = { "sandstone" } },
    { name = '3d_armor:helmet_gold',        chance = 0.3,  types = { "sandstone" } },
    { name = '3d_armor:leggings_gold',      chance = 0.3,  types = { "sandstone" } },
    { name = 'shields:shield_gold',         chance = 0.3,  types = { "sandstone" } },
    { name = '3d_armor:boots_brass',        chance = 0.3,  types = { "ice" } },
    { name = '3d_armor:chestplate_brass',   chance = 0.3,  types = { "ice" } },
    { name = '3d_armor:helmet_brass',       chance = 0.3,  types = { "ice" } },
    { name = '3d_armor:leggings_brass',     chance = 0.3,  types = { "ice" } },
    { name = 'shields:shield_brass',        chance = 0.3,  types = { "ice" } },
    { name = 'moreores:sword_brass',        chance = 0.3,  types = { "ice" } },
    { name = 'moreores:pick_brass',         chance = 0.3,  types = { "ice" } },
    { name = 'moreores:shovel_brass',       chance = 0.3,  types = { "ice" } },
    { name = 'mobs:lasso',                  chance = 0.1,  types = { "normal" } },
    { name = 'mobs:meat_raw',               chance = 0.4,  count = { 1, 4 },       types = { "normal" } },
    { name = 'mobs:nametag',                chance = 0.1,  count = { 1, 2 },       types = { "normal" } },
    { name = 'x_farming:melon',             chance = 0.4,  count = { 1, 4 },       types = { "normal" } },
    { name = 'x_farming:carrot_golden',     chance = 0.1,  count = { 1, 3 },       types = { "normal" } },
}

dungeon_loot.register(ctg_loot)
